# Generated by Django 5.0 on 2023-12-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_alter_album_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image_url',
            field=models.URLField(),
        ),
    ]
