# Generated by Django 5.0 on 2024-01-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_alter_album_album_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to='profile_pictures'),
            preserve_default=False,
        ),
    ]
